language: php

sudo: false

php:
- 7.0
- hhvm

env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=4.4 WP_MULTISITE=0
- WP_VERSION=4.3 WP_MULTISITE=0
- WP_VERSION=4.2 WP_MULTISITE=0
- WP_VERSION=4.1 WP_MULTISITE=0
- WP_VERSION=4.0 WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1
  exclude:
    - php: hhvm
      env: WP_VERSION=4.0 WP_MULTISITE=0

before_script:
- bash bin-wp/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
- if [[ $TRAVIS_PHP_VERSION != 'hhvm' && ( $TRAVIS_PHP_VERSION != '5.5'|| $WP_VERSION != 'latest'
  || $WP_MULTISITE != '0' ) ]]; then phpenv config-rm xdebug.ini; fi
- if [[ $TRAVIS_PHP_VERSION = '5.5' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0'
  ]]; then phpunit --coverage-clover=coverage.clover; else phpunit; fi

after_script:
- if [[ $TRAVIS_PHP_VERSION = '5.5' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0'
  ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
- if [[ $TRAVIS_PHP_VERSION = '5.5' && $WP_VERSION = 'latest' && $WP_MULTISITE = '0'
  ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover;
  fi

notifications: 
  hipchat: 
    rooms: 
      secure: VAdYhhXqaIdU+J4hca0fQydOHsWmtSbyupgOkvwT0akzslc5uGliodWkqkFuHCP+rGmeJIsoa/s9tj7YbmD7dlku7vva6d7KcX6W4jmHKlydBkEFzpO2N7w4ZGR501o428ZfLor/MVEKF/+FwRkMTT3RBDLNjcYOhFDGrvf2CyY=
